### ISSUE TITLE
Unrecoverable failure in required component budgie-wm.desktop when moving window

### ISSUE THREAD

**Issue by nhkode** [budgie-desktop/budgie-desktop#1563]
**Operating System**: Solus 3.9999
**Budgie version**: budgie-desktop v10.4-85-g36667bcb

**The issue encountered**
Budgie crashes and login screen is shown.

Probably relevant part from systemd journal:
`16:52:01 gnome-session-b: Unrecoverable failure in required component budgie-wm.desktop
16:52:01 budgie-wm: The program 'budgie-wm' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 4053 error_code 11 request_code 12 (core protocol) minor_code 0)`

dmesg:
`
[12055.280457] traps: budgie-wm[12428] trap int3 ip:7f082532a921 sp:7ffe470c5cb0 error:0 in libglib-2.0.so.0.5600.1[7f08252d8000+114000]
[12101.804921] traps: budgie-wm[12918] trap int3 ip:7f8690b2a921 sp:7ffdfbb4f2e0 error:0 in libglib-2.0.so.0.5600.1[7f8690ad8000+114000]
[12102.046671] budgie-daemon[12473]: segfault at 0 ip 00007fc7af3451fe sp 00007ffc7d04de50 error 6 in libwnck-3.so.0.3.0[7fc7af330000+3e000]
`

**Steps to reproduce the issue**`
Launch Shadow Tactics: Blades of Shogun from Steam. In the options disable full screen mode. Then it crashes the whole session when I try to move the window.

Video card: GeForce GTX 750 Ti
Driver: nvidia-glx-driver-current 390.87-260
monitor setup: monitor 1 on the right 1920x1200, monitor 2 on the left 2560x1440.

I'm not exactly sure if this is a budgie, X or driver problem. Just reporting it here because of the journal entry.

**Comment by alunux** [comment]
I don't have Shadow Tactics: Blades (maybe others too). I don't know if it's same issue or not with this one https://bugzilla.redhat.com/show_bug.cgi?id=1616269. Could you try the following operations and see if any of them causes a crash:

1) Launch and then exit glxgears
2) Launch and then exit Chrome or Chromium
3) Launch Chrome or Chromium and then move its window around. If you have more than one display, move its window between displays

**Comment by nhkode** [comment]
Okay, I've tried running Shadow Tactics and Oxenfree in mate. Oxenfree ran without issues, Shadow Tactics crashed but didn't take the whole xserver done.

Probably useless back trace from one of the crashes:
```
#0  0x00007f74de0471a1 in  () at /usr/lib/libgdk-3.so.0
#1  0x00007f74de051ed9 in  () at /usr/lib/libgdk-3.so.0
#2  0x00007f74dd94fcee in _XError () at /usr/lib/libX11.so.6
#3  0x00007f74dd8dce63 in  () at /usr/lib/libX11.so.6
#4  0x00007f74dd9500ad in _XReply () at /usr/lib/libX11.so.6
#5  0x00007f74dd9509ed in XSync () at /usr/lib/libX11.so.6
#6  0x00007f74de04654e in  () at /usr/lib/libgdk-3.so.0
#7  0x00007f74de021bef in  () at /usr/lib/libgdk-3.so.0
#8  0x00007f74df172379 in  () at /usr/lib/libmutter-2.so.0
#9  0x00007f74df175826 in  () at /usr/lib/libmutter-2.so.0
#10 0x00007f74df176878 in meta_window_actor_pre_paint ()
    at /usr/lib/libmutter-2.so.0
#11 0x00007f74df166a78 in  () at /usr/lib/libmutter-2.so.0
#12 0x00007f74df01ed92 in  () at /usr/lib64/mutter/libmutter-clutter-2.so
#13 0x00007f74df01fa47 in  () at /usr/lib64/mutter/libmutter-clutter-2.so
#14 0x00007f74debf4ec7 in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
#15 0x00007f74debf5100 in  () at /usr/lib/libglib-2.0.so.0
#16 0x00007f74debf5412 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#17 0x00007f74df18910c in meta_run () at /usr/lib/libmutter-2.so.0
#18 0x000000000040b845 in  ()
#19 0x00007f74de90301b in __libc_start_main () at /usr/lib/libc.so.6
#20 0x000000000040739a in  ()
```
