### ISSUE TITLE
build failure on debian experimental

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#921]
budgie-desktop 10.3.1 on debian experimental.

build log - http://debomatic-amd64.debian.net/distribution#experimental/budgie-desktop/10.3.1-1/buildlog

kind of curious error when it appears to be compiling the docs information by the looks of things

```
langs=ar@@ca@@cs@@da@@de_DE@@de@@en_GB@@en_US@@eo@@es_AR@@es_ES@@es_MX@@es@@eu@@fi@@fr_FR@@fr@@he@@hu@@id_ID@@id@@it_IT@@it@@ja_JP@@ko_KR@@lt@@lv@@nl_BE@@nl@@pl_PL@@pl@@pt_BR@@pt@@pt_PT@@ro@@ru@@sk@@sl@@sr_RS@latin@@sr_RS@@sv@@sv_SE@@tr@@uk@@zh_CN@@zh-Hant@@zh_TW'
Running custom install script '/usr/bin/python3 /usr/share/meson/meson --internal gtkdoc --sourcedir=/<<PKGBUILDDIR>> --builddir=/<<PKGBUILDDIR>>/debian/build --subdir=docs --headerdirs=/<<PKGBUILDDIR>>/src/plugin --mainfile=budgie-desktop-docs.sgml --modulename=budgie-desktop --mode=auto --scanargs=--ignore-headers=budgie-enums.h --gobjects-types-file=budgie-desktop.types --cflags=-I/<<PKGBUILDDIR>>/debian/build/src/plugin/. -I/<<PKGBUILDDIR>>/src/plugin/. -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpeas-1.0 -I/usr/include/gobject-introspection-1.0 --ldflags=-lbudgie-plugin -L/<<PKGBUILDDIR>>/debian/build/src/plugin -Wl,-rpath /<<PKGBUILDDIR>>/debian/build/src/plugin -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpeas-1.0 -lgmodule-2.0 -pthread -lgirepository-1.0 --cc=cc --ld=cc'WARNING: You are using 'ANSI_X3.4-1968' which is not a a Unicode-compatible locale.
WARNING: You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
WARNING: Please switch to a UTF-8 locale for your platform.
Building documentation for budgie-desktop
Traceback (most recent call last):
  File "/usr/share/meson/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/share/meson/meson", line 34, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 260, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 248, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/gtkdochelper.py", line 209, in run
    options.mode)
  File "/usr/share/meson/mesonbuild/scripts/gtkdochelper.py", line 162, in build_gtkdoc
    gtkdoc_run_check(fixref_cmd, abs_out)
  File "/usr/share/meson/mesonbuild/scripts/gtkdochelper.py", line 50, in gtkdoc_run_check
    p, out = Popen_safe(cmd, cwd=cwd, stderr=subprocess.STDOUT)[0:2]
  File "/usr/share/meson/mesonbuild/mesonlib.py", line 511, in Popen_safe
    o, e = p.communicate(write)
  File "/usr/lib/python3.5/subprocess.py", line 788, in communicate
    stdout = self.stdout.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 526: ordinal not in range(128)

Failed to run install script '/usr/bin/python3 /usr/share/meson/meson --internal gtkdoc --sourcedir=/<<PKGBUILDDIR>> --builddir=/<<PKGBUILDDIR>>/debian/build --subdir=docs --headerdirs=/<<PKGBUILDDIR>>/src/plugin --mainfile=budgie-desktop-docs.sgml --modulename=budgie-desktop --mode=auto --scanargs=--ignore-headers=budgie-enums.h --gobjects-types-file=budgie-desktop.types --cflags=-I/<<PKGBUILDDIR>>/debian/build/src/plugin/. -I/<<PKGBUILDDIR>>/src/plugin/. -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpeas-1.0 -I/usr/include/gobject-introspection-1.0 --ldflags=-lbudgie-plugin -L/<<PKGBUILDDIR>>/debian/build/src/plugin -Wl,-rpath /<<PKGBUILDDIR>>/debian/build/src/plugin -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpeas-1.0 -lgmodule-2.0 -pthread -lgirepository-1.0 --cc=cc --ld=cc'
FAILED: install 
'/usr/bin/python3' '/usr/share/meson/meson' '--internal' 'install' '/<<PKGBUILDDIR>>/debian/build/meson-private/install.dat'
```

**Comment by alunux** [comment]
You need to do this before `%meson_install`:
```
export LANG=en_US.utf8
export LC_ALL=en_US.utf8
```

**Comment by ikeydoherty** [comment]
Yeah an upstream meson limitation, we're doing the same thing in the Solus package (as `solbuild` enforces `LANG=C`)

**Comment by ikeydoherty** [comment]
Ya upstream meson nonsense can't deal with non unicode locales and the gtk-doc bits were fixed in git
